#!/bin/sh
rootdir=$(pwd)
init=false
binutils=false
gcc1=false
linux_headers=false
musl_headers=false

# init
if [ $init = true ]; then
	wget ftp.gnu.org/pub/gnu/binutils/binutils-2.38.tar.xz
	wget ftp.gnu.org/pub/gnu/gcc/gcc-11.2.0/gcc-11.2.0.tar.xz
	wget ftp.gnu.org/pub/gnu/gmp/gmp-6.2.1.tar.xz
	wget ftp.gnu.org/pub/gnu/mpc/mpc-1.2.1.tar.gz
	wget ftp.gnu.org/pub/gnu/mpfr/mpfr-4.1.0.tar.xz
	wget mirrors.edge.kernel.org/pub/linux/kernel/5.x/linux-5.16.10.tar.xz
	wget musl.libc.org/releases/musl-1.2.2.tar.gz

	xz -dv *.xz
	gunzip -dv *.gz

	for i in $(ls); do
		tar -xvf $i
	done

	rm -rf *.tar

	ln $rootdir/gmp-6.2.1 gcc-11.2.0/gmp -s
	ln $rootdir/mpc-1.2.1 gcc-11.2.0/mpc -s
	ln $rootdir/mpfr-4.1.0 gcc-11.2.0/mpfr -s
fi

# binutils
if [ $binutils = true ]; then
	cd binutils-2.38
	mkdir -p build
	cd build
	../configure --prefix=/opt/cross --target=i686-pocket-linux-musl --disable-mutilib
	make -j2
	sudo make install
	cd $rootdir
fi

# gcc c/c++ compilers
if [ $gcc1 = true ]; then
	cd gcc-11.2.0
	mkdir -p build
	cd build
	../configure --prefix=/opt/cross --target=i686-pocket-linux-musl --disable-multilib --enable-languages=c,c++
	make -j2 all-gcc
	sudo make install-gcc
	cd $rootdir
fi

# linux headers
if [ linux_headers = true ]; then
	cd linux-5.16.10
	make INSTALL_HDR_PATH=/opt/cross/i686-pocket-linux-musl headers_install
	sudo make INSTALL_HDR_PATH=/opt/cross/i686-pocket-linux-musl headers_install
	cd $rootdir
fi

# musl libc header files
if [ musl_headers = true ]; then
	cd musl-1.2.2
	./configure --prefix=/opt/cross/i686-pocket-linux-musl --target=i686-pocket-linux-musl --disable-multilib
	sudo cp -r include /opt/cross/i686-pocket-linux-musl/
	make -j2
	sudo make install
	cd $rootdir
fi

# gcc support lib
cd gcc-11.2.0/build
make -j2 all-target-libgcc
make install-target-libgcc
cd $rootdir

# musl libc.so
cd musl-1.2.2
make -j2
sudo make install
cd $rootdir

# gcc c++ library
cd gcc-11.2.0/build
make -j2
sudo make install
cd $rootdir
